version: "3.8"
services:
  api:
    image: alextrigolosvlg/dog_fast_api:v1
    ports:
      - "5555:5555"
    restart: always

  bot:
    image: alextrigolosvlg/dog_fast_api_bot:v1
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_API_URL=http://api:5555
    restart: always