version: "3.8"
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    restart: always

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_API_URL=http://api:5555
    restart: always